/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as SchemaDotjsonRouteImport } from "./routes/schema[.]json";
import { Route as DashboardRouteRouteImport } from "./routes/dashboard/route";
import { Route as HomeRouteRouteImport } from "./routes/_home/route";
import { Route as DashboardIndexRouteImport } from "./routes/dashboard/index";
import { Route as AuthIndexRouteImport } from "./routes/auth/index";
import { Route as HomeIndexRouteImport } from "./routes/_home/index";
import { Route as PrinterResumeIdRouteImport } from "./routes/printer/$resumeId";
import { Route as AuthLoginRouteImport } from "./routes/auth/login";
import { Route as ApiHealthRouteImport } from "./routes/api/health";
import { Route as UsernameSlugRouteImport } from "./routes/$username/$slug";
import { Route as BuilderResumeIdRouteRouteImport } from "./routes/builder/$resumeId/route";
import { Route as DashboardResumesIndexRouteImport } from "./routes/dashboard/resumes/index";
import { Route as BuilderResumeIdIndexRouteImport } from "./routes/builder/$resumeId/index";
import { Route as UploadsUserIdSplatRouteImport } from "./routes/uploads/$userId.$";
import { Route as DashboardSettingsProfileRouteImport } from "./routes/dashboard/settings/profile";
import { Route as ApiRpcSplatRouteImport } from "./routes/api/rpc.$";
import { Route as ApiOpenapiSplatRouteImport } from "./routes/api/openapi.$";
import { Route as ApiAuthSplatRouteImport } from "./routes/api/auth.$";

const SchemaDotjsonRoute = SchemaDotjsonRouteImport.update({
  id: "/schema.json",
  path: "/schema.json",
  getParentRoute: () => rootRouteImport,
} as any);
const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: "/dashboard",
  path: "/dashboard",
  getParentRoute: () => rootRouteImport,
} as any);
const HomeRouteRoute = HomeRouteRouteImport.update({
  id: "/_home",
  getParentRoute: () => rootRouteImport,
} as any);
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => DashboardRouteRoute,
} as any);
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: "/auth/",
  path: "/auth/",
  getParentRoute: () => rootRouteImport,
} as any);
const HomeIndexRoute = HomeIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => HomeRouteRoute,
} as any);
const PrinterResumeIdRoute = PrinterResumeIdRouteImport.update({
  id: "/printer/$resumeId",
  path: "/printer/$resumeId",
  getParentRoute: () => rootRouteImport,
} as any);
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: "/auth/login",
  path: "/auth/login",
  getParentRoute: () => rootRouteImport,
} as any);
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: "/api/health",
  path: "/api/health",
  getParentRoute: () => rootRouteImport,
} as any);
const UsernameSlugRoute = UsernameSlugRouteImport.update({
  id: "/$username/$slug",
  path: "/$username/$slug",
  getParentRoute: () => rootRouteImport,
} as any);
const BuilderResumeIdRouteRoute = BuilderResumeIdRouteRouteImport.update({
  id: "/builder/$resumeId",
  path: "/builder/$resumeId",
  getParentRoute: () => rootRouteImport,
} as any);
const DashboardResumesIndexRoute = DashboardResumesIndexRouteImport.update({
  id: "/resumes/",
  path: "/resumes/",
  getParentRoute: () => DashboardRouteRoute,
} as any);
const BuilderResumeIdIndexRoute = BuilderResumeIdIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => BuilderResumeIdRouteRoute,
} as any);
const UploadsUserIdSplatRoute = UploadsUserIdSplatRouteImport.update({
  id: "/uploads/$userId/$",
  path: "/uploads/$userId/$",
  getParentRoute: () => rootRouteImport,
} as any);
const DashboardSettingsProfileRoute =
  DashboardSettingsProfileRouteImport.update({
    id: "/settings/profile",
    path: "/settings/profile",
    getParentRoute: () => DashboardRouteRoute,
  } as any);
const ApiRpcSplatRoute = ApiRpcSplatRouteImport.update({
  id: "/api/rpc/$",
  path: "/api/rpc/$",
  getParentRoute: () => rootRouteImport,
} as any);
const ApiOpenapiSplatRoute = ApiOpenapiSplatRouteImport.update({
  id: "/api/openapi/$",
  path: "/api/openapi/$",
  getParentRoute: () => rootRouteImport,
} as any);
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: "/api/auth/$",
  path: "/api/auth/$",
  getParentRoute: () => rootRouteImport,
} as any);

export interface FileRoutesByFullPath {
  "/": typeof HomeIndexRoute;
  "/dashboard": typeof DashboardRouteRouteWithChildren;
  "/schema.json": typeof SchemaDotjsonRoute;
  "/builder/$resumeId": typeof BuilderResumeIdRouteRouteWithChildren;
  "/$username/$slug": typeof UsernameSlugRoute;
  "/api/health": typeof ApiHealthRoute;
  "/auth/login": typeof AuthLoginRoute;
  "/printer/$resumeId": typeof PrinterResumeIdRoute;
  "/auth/": typeof AuthIndexRoute;
  "/dashboard/": typeof DashboardIndexRoute;
  "/api/auth/$": typeof ApiAuthSplatRoute;
  "/api/openapi/$": typeof ApiOpenapiSplatRoute;
  "/api/rpc/$": typeof ApiRpcSplatRoute;
  "/dashboard/settings/profile": typeof DashboardSettingsProfileRoute;
  "/uploads/$userId/$": typeof UploadsUserIdSplatRoute;
  "/builder/$resumeId/": typeof BuilderResumeIdIndexRoute;
  "/dashboard/resumes/": typeof DashboardResumesIndexRoute;
}
export interface FileRoutesByTo {
  "/schema.json": typeof SchemaDotjsonRoute;
  "/$username/$slug": typeof UsernameSlugRoute;
  "/api/health": typeof ApiHealthRoute;
  "/auth/login": typeof AuthLoginRoute;
  "/printer/$resumeId": typeof PrinterResumeIdRoute;
  "/": typeof HomeIndexRoute;
  "/auth": typeof AuthIndexRoute;
  "/dashboard": typeof DashboardIndexRoute;
  "/api/auth/$": typeof ApiAuthSplatRoute;
  "/api/openapi/$": typeof ApiOpenapiSplatRoute;
  "/api/rpc/$": typeof ApiRpcSplatRoute;
  "/dashboard/settings/profile": typeof DashboardSettingsProfileRoute;
  "/uploads/$userId/$": typeof UploadsUserIdSplatRoute;
  "/builder/$resumeId": typeof BuilderResumeIdIndexRoute;
  "/dashboard/resumes": typeof DashboardResumesIndexRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/_home": typeof HomeRouteRouteWithChildren;
  "/dashboard": typeof DashboardRouteRouteWithChildren;
  "/schema.json": typeof SchemaDotjsonRoute;
  "/builder/$resumeId": typeof BuilderResumeIdRouteRouteWithChildren;
  "/$username/$slug": typeof UsernameSlugRoute;
  "/api/health": typeof ApiHealthRoute;
  "/auth/login": typeof AuthLoginRoute;
  "/printer/$resumeId": typeof PrinterResumeIdRoute;
  "/_home/": typeof HomeIndexRoute;
  "/auth/": typeof AuthIndexRoute;
  "/dashboard/": typeof DashboardIndexRoute;
  "/api/auth/$": typeof ApiAuthSplatRoute;
  "/api/openapi/$": typeof ApiOpenapiSplatRoute;
  "/api/rpc/$": typeof ApiRpcSplatRoute;
  "/dashboard/settings/profile": typeof DashboardSettingsProfileRoute;
  "/uploads/$userId/$": typeof UploadsUserIdSplatRoute;
  "/builder/$resumeId/": typeof BuilderResumeIdIndexRoute;
  "/dashboard/resumes/": typeof DashboardResumesIndexRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | "/"
    | "/dashboard"
    | "/schema.json"
    | "/builder/$resumeId"
    | "/$username/$slug"
    | "/api/health"
    | "/auth/login"
    | "/printer/$resumeId"
    | "/auth/"
    | "/dashboard/"
    | "/api/auth/$"
    | "/api/openapi/$"
    | "/api/rpc/$"
    | "/dashboard/settings/profile"
    | "/uploads/$userId/$"
    | "/builder/$resumeId/"
    | "/dashboard/resumes/";
  fileRoutesByTo: FileRoutesByTo;
  to:
    | "/schema.json"
    | "/$username/$slug"
    | "/api/health"
    | "/auth/login"
    | "/printer/$resumeId"
    | "/"
    | "/auth"
    | "/dashboard"
    | "/api/auth/$"
    | "/api/openapi/$"
    | "/api/rpc/$"
    | "/dashboard/settings/profile"
    | "/uploads/$userId/$"
    | "/builder/$resumeId"
    | "/dashboard/resumes";
  id:
    | "__root__"
    | "/_home"
    | "/dashboard"
    | "/schema.json"
    | "/builder/$resumeId"
    | "/$username/$slug"
    | "/api/health"
    | "/auth/login"
    | "/printer/$resumeId"
    | "/_home/"
    | "/auth/"
    | "/dashboard/"
    | "/api/auth/$"
    | "/api/openapi/$"
    | "/api/rpc/$"
    | "/dashboard/settings/profile"
    | "/uploads/$userId/$"
    | "/builder/$resumeId/"
    | "/dashboard/resumes/";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  HomeRouteRoute: typeof HomeRouteRouteWithChildren;
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren;
  SchemaDotjsonRoute: typeof SchemaDotjsonRoute;
  BuilderResumeIdRouteRoute: typeof BuilderResumeIdRouteRouteWithChildren;
  UsernameSlugRoute: typeof UsernameSlugRoute;
  ApiHealthRoute: typeof ApiHealthRoute;
  AuthLoginRoute: typeof AuthLoginRoute;
  PrinterResumeIdRoute: typeof PrinterResumeIdRoute;
  AuthIndexRoute: typeof AuthIndexRoute;
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute;
  ApiOpenapiSplatRoute: typeof ApiOpenapiSplatRoute;
  ApiRpcSplatRoute: typeof ApiRpcSplatRoute;
  UploadsUserIdSplatRoute: typeof UploadsUserIdSplatRoute;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/schema.json": {
      id: "/schema.json";
      path: "/schema.json";
      fullPath: "/schema.json";
      preLoaderRoute: typeof SchemaDotjsonRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/dashboard": {
      id: "/dashboard";
      path: "/dashboard";
      fullPath: "/dashboard";
      preLoaderRoute: typeof DashboardRouteRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/_home": {
      id: "/_home";
      path: "";
      fullPath: "/";
      preLoaderRoute: typeof HomeRouteRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/dashboard/": {
      id: "/dashboard/";
      path: "/";
      fullPath: "/dashboard/";
      preLoaderRoute: typeof DashboardIndexRouteImport;
      parentRoute: typeof DashboardRouteRoute;
    };
    "/auth/": {
      id: "/auth/";
      path: "/auth";
      fullPath: "/auth/";
      preLoaderRoute: typeof AuthIndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/_home/": {
      id: "/_home/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof HomeIndexRouteImport;
      parentRoute: typeof HomeRouteRoute;
    };
    "/printer/$resumeId": {
      id: "/printer/$resumeId";
      path: "/printer/$resumeId";
      fullPath: "/printer/$resumeId";
      preLoaderRoute: typeof PrinterResumeIdRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/auth/login": {
      id: "/auth/login";
      path: "/auth/login";
      fullPath: "/auth/login";
      preLoaderRoute: typeof AuthLoginRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/api/health": {
      id: "/api/health";
      path: "/api/health";
      fullPath: "/api/health";
      preLoaderRoute: typeof ApiHealthRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/$username/$slug": {
      id: "/$username/$slug";
      path: "/$username/$slug";
      fullPath: "/$username/$slug";
      preLoaderRoute: typeof UsernameSlugRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/builder/$resumeId": {
      id: "/builder/$resumeId";
      path: "/builder/$resumeId";
      fullPath: "/builder/$resumeId";
      preLoaderRoute: typeof BuilderResumeIdRouteRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/dashboard/resumes/": {
      id: "/dashboard/resumes/";
      path: "/resumes";
      fullPath: "/dashboard/resumes/";
      preLoaderRoute: typeof DashboardResumesIndexRouteImport;
      parentRoute: typeof DashboardRouteRoute;
    };
    "/builder/$resumeId/": {
      id: "/builder/$resumeId/";
      path: "/";
      fullPath: "/builder/$resumeId/";
      preLoaderRoute: typeof BuilderResumeIdIndexRouteImport;
      parentRoute: typeof BuilderResumeIdRouteRoute;
    };
    "/uploads/$userId/$": {
      id: "/uploads/$userId/$";
      path: "/uploads/$userId/$";
      fullPath: "/uploads/$userId/$";
      preLoaderRoute: typeof UploadsUserIdSplatRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/dashboard/settings/profile": {
      id: "/dashboard/settings/profile";
      path: "/settings/profile";
      fullPath: "/dashboard/settings/profile";
      preLoaderRoute: typeof DashboardSettingsProfileRouteImport;
      parentRoute: typeof DashboardRouteRoute;
    };
    "/api/rpc/$": {
      id: "/api/rpc/$";
      path: "/api/rpc/$";
      fullPath: "/api/rpc/$";
      preLoaderRoute: typeof ApiRpcSplatRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/api/openapi/$": {
      id: "/api/openapi/$";
      path: "/api/openapi/$";
      fullPath: "/api/openapi/$";
      preLoaderRoute: typeof ApiOpenapiSplatRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/api/auth/$": {
      id: "/api/auth/$";
      path: "/api/auth/$";
      fullPath: "/api/auth/$";
      preLoaderRoute: typeof ApiAuthSplatRouteImport;
      parentRoute: typeof rootRouteImport;
    };
  }
}

interface HomeRouteRouteChildren {
  HomeIndexRoute: typeof HomeIndexRoute;
}

const HomeRouteRouteChildren: HomeRouteRouteChildren = {
  HomeIndexRoute: HomeIndexRoute,
};

const HomeRouteRouteWithChildren = HomeRouteRoute._addFileChildren(
  HomeRouteRouteChildren,
);

interface DashboardRouteRouteChildren {
  DashboardIndexRoute: typeof DashboardIndexRoute;
  DashboardSettingsProfileRoute: typeof DashboardSettingsProfileRoute;
  DashboardResumesIndexRoute: typeof DashboardResumesIndexRoute;
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardSettingsProfileRoute: DashboardSettingsProfileRoute,
  DashboardResumesIndexRoute: DashboardResumesIndexRoute,
};

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
);

interface BuilderResumeIdRouteRouteChildren {
  BuilderResumeIdIndexRoute: typeof BuilderResumeIdIndexRoute;
}

const BuilderResumeIdRouteRouteChildren: BuilderResumeIdRouteRouteChildren = {
  BuilderResumeIdIndexRoute: BuilderResumeIdIndexRoute,
};

const BuilderResumeIdRouteRouteWithChildren =
  BuilderResumeIdRouteRoute._addFileChildren(BuilderResumeIdRouteRouteChildren);

const rootRouteChildren: RootRouteChildren = {
  HomeRouteRoute: HomeRouteRouteWithChildren,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  SchemaDotjsonRoute: SchemaDotjsonRoute,
  BuilderResumeIdRouteRoute: BuilderResumeIdRouteRouteWithChildren,
  UsernameSlugRoute: UsernameSlugRoute,
  ApiHealthRoute: ApiHealthRoute,
  AuthLoginRoute: AuthLoginRoute,
  PrinterResumeIdRoute: PrinterResumeIdRoute,
  AuthIndexRoute: AuthIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiOpenapiSplatRoute: ApiOpenapiSplatRoute,
  ApiRpcSplatRoute: ApiRpcSplatRoute,
  UploadsUserIdSplatRoute: UploadsUserIdSplatRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();

import type { getRouter } from "./router.tsx";
import type { createStart } from "@tanstack/react-start";
declare module "@tanstack/react-start" {
  interface Register {
    ssr: true;
    router: Awaited<ReturnType<typeof getRouter>>;
  }
}
